//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public string UserName { get; set; }
        public string Password { get; set; }
        public bool Connected { get; set; }
        public bool Enabled { get; set; }
        public string IP { get; set; }
        public string Port { get; set; }
    }
}
